Completed the PIN Based Authentication in the settings feature!
SankethBK/diaryvault pull request #161
Opened 2023-11-29 17:48 UTC by LujainAlMansoori

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
The PIN-based authentication feature is complete in the settings. The user is able to select to log in through a pin from the setting because we added a Enable PIN-based login. Once this takes place, a pop up comes up and collects the 4 digit pin from the user. We added a validation where only keyword numbers show up and we check if both PINs are matching, otherwise display error in a error message. Once that happens the user id and hashed pin is saved into a PINAuthRepository in the form of key:value pairs.

## Featured Covered in this PR

- [X] Task 1
- [X] Task 2

## Related Tickets & Documents

- Related Issue #71
- Closes #71

## Screenshots, Recordings
<img width="1470" alt="Screenshot 2023-11-29 at 8 42 13 PM" src="https://github.com/SankethBK/diaryvault/assets/122256965/c06bc90c-f61e-4351-bb87-c13d2378c5d1">
![Uploading Screenshot
<img width="1470" alt="Screenshot 2023-11-29 at 8 42 28 PM" src="https://github.com/SankethBK/diaryvault/assets/122256965/c22acf9c-0d5a-4c02-b8e7-2b4826a3275b">
<img width="1289" alt="Screenshot 2023-11-29 at 8 45 51 PM" src="https://github.com/SankethBK/diaryvault/assets/122256965/072e732f-4ce3-4109-a8b6-2fd6896c8899">
 2023-11-29 at 8.42.21 PM.png…]()

## Tested Feature??

- [ ] In Real Device.
- [X] In Emulator

2023-11-30 16:27 UTC, mbfannan approved these changes
Looks great, wonderful work all contributers!

2023-11-30 18:54 UTC, SankethBK commented
Thanks for contributing! I'll review by tomorrow

2023-12-01 21:30 UTC, LujainAlMansoori commented
Sure, thanks!

2023-12-02 17:04 UTC, mbfannan commented
@SankethBK any updates?

2023-12-02 20:02 UTC, SankethBK requested changes
Nice job! I have added minor comments, check them once

2023-12-02 20:02 UTC, SankethBK commented on lib/features/auth/presentation/widgets/security_settings.dart
> +
This switch should be enabled only if PIN is successfully set, currently it gets enabled if we enter mismatched pins

2023-12-02 20:05 UTC, mbfannan approved these changes
Thanks for the changes!

2023-12-02 20:06 UTC, LujainAlMansoori commented
Thanks for your changes, I resolved them!

2023-12-03 14:21 UTC, mbfannan commented
Hi @SankethBK and @LujainAlMansoori took me a while because some formatting and syntax errors didn't appear before, but everything should be alright now to merge thanks! Once it's merged I'll get on to issue #72 and I already got a start on it thanks!

2023-12-03 16:09 UTC, mbfannan reviewed
With the additional changes made hopefully everything should be fine, just to note however another push was made to change file name of "PINAuthRepository.dart" due to linter error along with other formatting issues resolved.

2023-12-03 17:23 UTC, SankethBK commented on lib/features/auth/presentation/widgets/security_settings.dart
> +                            if (value) {
Use value == true, improves readability

2023-12-03 17:25 UTC, SankethBK commented on lib/features/auth/presentation/widgets/security_settings.dart
> +                              );
Currently the switch gets enabled even if pin is not successfully set, you can return a boolean value from `pinResetPopup` using `Navigator.pop(context)` and enable this switch only if its true. You can use `passwordLoginPopup` as reference for returning data from `Navigator.pop(context)`

2023-12-03 17:26 UTC, SankethBK commented on pubspec.lock
> -packages:
We need this file, don't delete it

2023-12-03 17:38 UTC, SankethBK commented
Hey @mbfannan , I have added minor comments, I have changed the target branch to `pin_authentication` as we need to have part 2 as well before releasing it. Feel free to merge this to `pin_authentication` branch, you can resolve the comments later. 

Thanks @mbfannan @LujainAlMansoori for your contribution!

2023-12-04 22:09 UTC, mbfannan commented
Hi @SankethBK, @LujainAlMansoori  and I resolved task 1 for issue #71 and completed issue #72. Hope everything's alright to merge!

2023-12-04 22:24 UTC, LujainAlMansoori commented
Yes, we completed both issues, issues #71 and #72  and they should be ready to be merged!

2023-12-05 11:52 UTC, mbfannan commented
Hi, @SankethBK do you have any updates? We're doing this as part of a Software Engineering course at Carnegie Mellon University, and our deadline to continue contributing would be at the latest by tomorrow evening. So please let us know if we can help with any more changes to merge, thanks!

2023-12-05 12:04 UTC, SankethBK commented
Hey @mbfannan I'll review in next 2-3 hours.

2023-12-05 12:57 UTC, mbfannan commented
> Hey @mbfannan I'll review in next 2-3 hours.

Great thanks!

2023-12-05 13:59 UTC, SankethBK commented
This is great! thanks @mbfannan @LujainAlMansoori for choosing this project to contribute.

2023-12-05 13:59 UTC, merged